FROM registry.access.redhat.com/ubi9/ubi-minimal

LABEL maintainer="Nishant contact@nishko.co"
ENV TZ=Asia/Kolkata
SHELL ["/bin/bash", "-lc"]

RUN microdnf update -y \
 && microdnf install -y \
    git \
    sudo \
    shadow-utils \
    tar \
    which \
 && microdnf clean all

ARG USERNAME=nishko
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid ${USER_GID} ${USERNAME} \
 && useradd -m --uid ${USER_UID} --gid ${USER_GID} -s /bin/bash ${USERNAME} \
 && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME} \
 && chmod 0440 /etc/sudoers.d/${USERNAME}

WORKDIR /workspaces
USER ${USERNAME}
ENV HOME=/home/${USERNAME}

CMD ["bash"]